export const members = [
  {
    id: 1,
    initials: 'SZ',
    color: '#3D6B9A',
    zhName: '张嘉嘉',
    enName: 'Serena Zhang',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Said Business School',
    degree: 'MBA',
    company: 'Atlas Capital',
    role: '合伙人',
    industry: '风险投资',
    city: '上海',
    intents: ['寻找合作', '结识朋友'],
    intentColors: ['teal', 'gray'],
    quote: '在为早期硬科技项目找联合创始人，也想认识同频的人。',
    about: '专注半导体与机器人方向的早期投资，看了五年硬科技。喜欢爬山、古典乐和一切动手做的东西。',
  },
  {
    id: 2,
    initials: 'WS',
    color: '#B5713A',
    zhName: '苏晚',
    enName: 'Wan Su',
    school: '剑桥',
    schoolEn: 'Cambridge',
    college: 'Trinity College',
    degree: '经济学',
    company: '茶饮品牌「阿屿」',
    role: '创始人',
    industry: '消费品',
    city: '北京',
    intents: ['商务对接', '结识朋友'],
    intentColors: ['gold', 'gray'],
    quote: '想认识擅长供应链与零售渠道的人，一起把东方茶做出去。',
    about: '剑桥经济系毕业，回国后创立东方茶品牌阿屿，专注供应链与海外拓展。',
  },
  {
    id: 3,
    initials: 'AY',
    color: '#8B4A6B',
    zhName: '叶知秋',
    enName: 'Autumn Ye',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Merton College',
    degree: '英文文学',
    company: '独立出版人',
    role: '主理人',
    industry: '内容 / 出版',
    city: '上海',
    intents: ['结识朋友', '寻找合作'],
    intentColors: ['gray', 'teal'],
    quote: '在做一本关于华人离散经验的独立杂志，想认识有故事的人。',
    about: '牛津文学系，现做独立出版与内容策划。相信好故事改变世界。',
  },
  {
    id: 4,
    initials: 'LR',
    color: '#6B7A5A',
    zhName: '李文远',
    enName: 'Leonard Richards',
    school: '剑桥',
    schoolEn: 'Cambridge',
    college: 'King\'s College',
    degree: '计算机科学',
    company: 'Meridian AI',
    role: '联合创始人',
    industry: '人工智能 / 投资',
    city: '伦敦',
    intents: ['寻找合作', '商务对接'],
    intentColors: ['teal', 'gold'],
    quote: '在做AI应用层的产品落地与商业化，看平台建设与增长方向。',
    about: '剑桥计算机，连续创业者。期待下次主题沙龙继续聊。',
  },
  {
    id: 5,
    initials: 'ZM',
    color: '#4A6B7A',
    zhName: '周牧',
    enName: 'Zhou Mu',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Green Templeton',
    degree: '公共政策',
    company: '城市气候智库',
    role: '研究员',
    industry: '公共政策 / 气候',
    city: '北京',
    intents: ['寻找合作', '结识朋友'],
    intentColors: ['teal', 'gray'],
    quote: '在做城市与气候议题，想找跨界、能把想法落地的伙伴。',
    about: '牛津公共政策，专注城市气候治理研究，希望连接政策与实践。',
  },
];

export const myProfile = {
  initials: 'SE',
  color: '#0D1B2A',
  zhName: '牛津',
  enName: 'serena',
  school: 'University of Oxford',
  college: 'Trinity College',
  background: 'investment',
  industry: 'investment',
  role: '合伙人',
  city: '上海',
  intents: ['结识朋友', '寻找合作'],
  quote: '希望认识有趣的你，一起探索合作的可能性。',
};
