export const members = [
  {
    id: 1,
    initials: 'SZ',
    color: '#3D6B9A',
    zhName: '张嘉嘉',
    enName: 'Serena Zhang',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Said Business School',
    degree: 'MBA',
    degreeEn: 'MBA',
    company: 'Atlas Capital',
    role: '合伙人',
    roleEn: 'Partner',
    industry: '风险投资',
    industryEn: 'Venture Capital',
    city: '上海',
    cityEn: 'Shanghai',
    intents: ['寻找合作', '结识朋友'],
    quote: '在为早期硬科技项目找联合创始人，也想认识同频的人。',
    quoteEn: 'Looking for a co-founder for an early-stage hard-tech project, and hoping to meet like-minded people.',
    about: '专注半导体与机器人方向的早期投资，看了五年硬科技。喜欢爬山、古典乐和一切动手做的东西。',
    aboutEn: 'Five years in early-stage hard-tech investing, focused on semiconductors and robotics. Loves hiking, classical music, and building things with her hands.',
  },
  {
    id: 2,
    initials: 'WS',
    color: '#B5713A',
    zhName: '苏晚',
    enName: 'Wan Su',
    school: '剑桥',
    schoolEn: 'Cambridge',
    college: 'Trinity College',
    degree: '经济学',
    degreeEn: 'Economics',
    company: 'Ayu Tea',
    role: '创始人',
    roleEn: 'Founder',
    industry: '消费品',
    industryEn: 'Consumer Goods',
    city: '北京',
    cityEn: 'Beijing',
    intents: ['商务对接', '结识朋友'],
    quote: '想认识擅长供应链与零售渠道的人，一起把东方茶做出去。',
    quoteEn: 'Looking to meet people with supply chain and retail expertise to help bring Eastern tea to the world.',
    about: '剑桥经济系毕业，回国后创立东方茶品牌阿屿，专注供应链与海外拓展。',
    aboutEn: 'Cambridge Economics graduate. Founded Ayu Tea after returning to China, focused on supply chain and international expansion.',
  },
  {
    id: 3,
    initials: 'AY',
    color: '#8B4A6B',
    zhName: '叶知秋',
    enName: 'Autumn Ye',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Merton College',
    degree: '英文文学',
    degreeEn: 'English Literature',
    company: 'Independent Publisher',
    role: '主理人',
    roleEn: 'Editor-in-Chief',
    industry: '内容 / 出版',
    industryEn: 'Content / Publishing',
    city: '上海',
    cityEn: 'Shanghai',
    intents: ['结识朋友', '寻找合作'],
    quote: '在做一本关于华人离散经验的独立杂志，想认识有故事的人。',
    quoteEn: 'Making an independent magazine about the Chinese diaspora experience — looking to meet people with stories to tell.',
    about: '牛津文学系，现做独立出版与内容策划。相信好故事改变世界。',
    aboutEn: 'Oxford English Literature. Now doing independent publishing and content. Believes good stories change the world.',
  },
  {
    id: 4,
    initials: 'LR',
    color: '#6B7A5A',
    zhName: '李文远',
    enName: 'Leonard Richards',
    school: '剑桥',
    schoolEn: 'Cambridge',
    college: "King's College",
    degree: '计算机科学',
    degreeEn: 'Computer Science',
    company: 'Meridian AI',
    role: '联合创始人',
    roleEn: 'Co-founder',
    industry: '人工智能 / 投资',
    industryEn: 'AI / Investment',
    city: '伦敦',
    cityEn: 'London',
    intents: ['寻找合作', '商务对接'],
    quote: '在做AI应用层的产品落地与商业化，看平台建设与增长方向。',
    quoteEn: 'Working on AI application-layer products and commercialisation — interested in platform building and growth.',
    about: '剑桥计算机，连续创业者。期待下次主题沙龙继续聊。',
    aboutEn: 'Cambridge Computer Science. Serial entrepreneur. Looking forward to continuing the conversation at the next salon.',
  },
  {
    id: 5,
    initials: 'ZM',
    color: '#4A6B7A',
    zhName: '周牧',
    enName: 'Zhou Mu',
    school: '牛津',
    schoolEn: 'Oxford',
    college: 'Green Templeton',
    degree: '公共政策',
    degreeEn: 'Public Policy',
    company: 'Urban Climate Institute',
    role: '研究员',
    roleEn: 'Researcher',
    industry: '公共政策 / 气候',
    industryEn: 'Public Policy / Climate',
    city: '北京',
    cityEn: 'Beijing',
    intents: ['寻找合作', '结识朋友'],
    quote: '在做城市与气候议题，想找跨界、能把想法落地的伙伴。',
    quoteEn: 'Working on urban climate issues — looking for cross-sector partners who can help turn ideas into action.',
    about: '牛津公共政策，专注城市气候治理研究，希望连接政策与实践。',
    aboutEn: 'Oxford Public Policy. Focused on urban climate governance research, bridging policy and practice.',
  },
]

export const myProfile = {
  initials: 'SE',
  color: '#0D1B2A',
  zhName: '牛津',
  enName: 'serena',
  school: 'University of Oxford',
  college: 'Trinity College',
  background: 'Investment',
  industry: 'Investment',
  role: 'Partner',
  city: 'Shanghai',
  intents: ['结识朋友', '寻找合作'],
  quote: '希望认识有趣的你，一起探索合作的可能性。',
  quoteEn: 'Hoping to meet interesting people and explore what we might create together.',
}
